version: "3.9"
services:
  mysql-items:
    restart: always
    container_name: "items-mysql"
    image: mysql:latest
    ports:
      - 6001:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - items-data:/var/lib/mysql # named volume for persistent data
      - ./items-schema.sql:/docker-entrypoint-initdb.d/schema.sql # change when putting this in the root directory as it uses relative pathing.

volumes:
  items-data: # definition of the named volume
